set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

include(${CMAKE_CURRENT_LIST_DIR}/GNU.C.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Clang.C.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Intel.C.cmake)
